### ISSUE TITLE
Chromatic number is never 1

### ISSUE THREAD

**Issue by HKH515** [rostam/GTea#5]
Given a disconnected graph,  or just a single vertex graph, it reports the chromatic number as 2, should be 1.

**Comment by rostam** [comment]
I think this error happens only when the graph does not have any edge.
So I compute this case separately and return 1:
https://github.com/rostam/GTea/commit/ec455b5f062d17ad4ef8abcfe3b6e49eedec99a7
 
Is there any other example that does not work?

**Comment by HKH515** [comment]
no i think this only happens when there are no edge, if i find any more I'll let you know

**Comment by rostam** [comment]
Just in case, the vertex coloring is NP-Complete as you may know. So, this algorithm would take long for large graphs. If you need an estimation of chromatic number and coloring for large graphs,  we can simply implement a heuristic.

**Comment by HKH515** [comment]
One solution would to cache results when running algorithms, and when a graph is drawn again we can check for isomorphisms for the computation results, but that is quite a drastic change to the codebase.

**Comment by rostam** [comment]
Checking graph isomorphism is also a hard problem. 
My suggestion is to use heuristics. 
They have convincing results in a reasonable time.
The implementation is also very easy:
https://en.wikipedia.org/wiki/Greedy_coloring

**Comment by HKH515** [comment]
That sounds like a good way to do it, but it does not always give correct results, right?

**Comment by rostam** [comment]
It always gives a valid coloring which means no connected vertices have
the same color. However, the number of colors can be higher than the correct chromatic number.

I implemented a greedy coloring here:
https://github.com/rostam/GTea/blob/master/src/main/java/graphtea/extensions/reports/GreedyColoring.java

Watch the following video which shows that the results are convincing:
https://www.dropbox.com/s/ib7wnsl6ykt8j6s/coloring.ogv?dl=0
or 
https://www.dropbox.com/s/20koe0twoofxfcn/coloring.mp4?dl=0

I also add a small button which shows that coloring on the graph.
You can see what I mean in that video.

**Comment by HKH515** [comment]
Looks good, but yeah what I meant by not giving always a correct results is that it doesn't always give the lowest possible number of colors, this is just something that i noticed and wanted to bring up since we are implementing directed/undirected drawing in GTea.

**Comment by rostam** [comment]
Yes. It is great that you mentioned it.
I think we can close this issue. What do you think?

**Comment by HKH515** [comment]
yeah
